from typing import List, Tuple
from .names import InternalItemIDs as IDs

class InternalItem:
    def __init__(self, itemID, amount):
        self.itemID = itemID
        self.amount = amount

# Dungeon ID 1
vfsz_treasure1 = [InternalItem(IDs.HEALING_GRASS, 2)]
vfsz_treasure2 = [InternalItem(IDs.HEALING_GRASS, 1)]
vfsz_treasure3 = [InternalItem(IDs.CHIPS_PREORDERCAMPAIGN, 4)]
vfsz_treasure4 = [InternalItem(IDs.FRAGMENT_LIFE, 1)]

#Dungeon ID 2
stationArea_treasure1 = [InternalItem(IDs.HEALING_GRASS, 2)]
stationArea_treasure2 = [InternalItem(IDs.FRAGMENT_LIFE, 1)]
stationArea_treasure3 = [InternalItem(IDs.ARMOR_LEATHERARMLET, 1)]
stationArea_treasure4 = [InternalItem(IDs.BOOSTER_STR, 1)]

#Dungeon ID 3
zeca1_treasure1 = [InternalItem(IDs.PLAN_TACHI, 1)]
zeca1_treasure2 = [InternalItem(IDs.PLAN_NEPBULL, 1)]
zeca1_treasure3 = [InternalItem(IDs.HEALING_GRASS, 2)]
zeca1_treasure4 = [InternalItem(IDs.FRAGMENT_LIFE, 1)]
zeca1_treasure5 = [InternalItem(IDs.HEALING_GRASS, 3), InternalItem(IDs.PLAN_CHANGEWORLDBGM, 1)]
zeca1_treasure6 = [InternalItem(IDs.FRAGMENT_LIFE, 1)]

#Dungeon ID 4
jetSetRange1_treasure1 = [InternalItem(IDs.PLAN_YOUTHBANDAGE, 1), InternalItem(IDs.PLAN_THESOULOFEVIL, 1)]
jetSetRange1_treasure2 = [InternalItem(IDs.PLAN_PARALAXIN, 1), InternalItem(IDs. PLAN_GETTHEEPAINTNG, 1)]
jetSetRange1_treasure3 = [InternalItem(IDs.HEALING_GRASS, 2)]
jetSetRange1_treasure4 = [InternalItem(IDs.FRAGMENT_LIFE, 1), InternalItem(IDs.BOOSTER_STR, 1)]

#Dungeon ID 5
jetSetRange2_treasure1 = [InternalItem(IDs.PARALAXIN, 3), InternalItem(IDs.PLAN_HAIRANDFASHION, 1)]
jetSetRange2_treasure2 = [InternalItem(IDs.CHIPS_SPORTS, 4)]
jetSetRange2_treasure3 = [InternalItem(IDs.BOOSTER_INT, 1)]
jetSetRange2_treasure4 = [InternalItem(IDs.CHIPS_FREESCENARIO, 4)]
jetSetRange2_treasure5 = [InternalItem(IDs.FRAGMENT_LIFE, 1)]

#Dungeon ID 6
wanderersCave_treasure1 = [InternalItem(IDs.PLAN_DOGOODUDE, 1), InternalItem(IDs.PLAN_ILOVECATS, 1)]
wanderersCave_treasure2 = [InternalItem(IDs.PLAN_HEALINGPOD, 1)]
wanderersCave_treasure3 = [InternalItem(IDs.CHIPS_RPG, 4)]
wanderersCave_treasure4 = [InternalItem(IDs.FRAGMENT_LIFE, 2)]
wanderersCave_treasure5 = [InternalItem(IDs.BOOSTER_STR, 1), InternalItem(IDs.ARMOR_STEELARMLET, 1)]

#Dungeon ID 7
wanderersCaveDepths_treasure1 = [InternalItem(IDs.BOOSTER_AGI, 1), InternalItem(IDs.PLAN_THECELEB, 1)]
wanderersCaveDepths_treasure2 = [InternalItem(IDs.SPCHARGER, 1)]
wanderersCaveDepths_treasure3 = [InternalItem(IDs.CHIPS_WAHAHAHAHA, 4)]
wanderersCaveDepths_treasure4 = [InternalItem(IDs.HEALING_POD, 2)]

#Dungeon ID 8
bandicrash_treasure1 = [InternalItem(IDs.PLAN_CLAYMORE, 1), InternalItem(IDs.PLAN_HATSOFTHEWORLD, 1)]
bandicrash_treasure2 = [InternalItem(IDs.BOOSTER_STR, 3)]
bandicrash_treasure3 = [InternalItem(IDs.CHIPS_DIESOFAST, 4)]
bandicrash_treasure4 = [InternalItem(IDs.CHIPS_ORTHODOX, 4)]
bandicrash_treasure5 = [InternalItem(IDs.CHIPS_NONRPGGROWTH, 4)]

#Dungeon ID 9
kuzaratFacility1_treasure1 = [InternalItem(IDs.PLAN_BRONZESWORD, 1)]
kuzaratFacility1_treasure2 = [InternalItem(IDs.TUFFMIL, 2)]
kuzaratFacility1_treasure3 = [InternalItem(IDs.SPCHARGER, 2)]
kuzaratFacility1_treasure4 = [InternalItem(IDs.CHIPS_CASUALORIENTED, 4)]
kuzaratFacility1_treasure5 = [InternalItem(IDs.FRAGMENT_LIFE, 1)]

#Dungeon ID 10
kuzaratFacility2_treasure1 = [InternalItem(IDs.SPCHARGER, 1), InternalItem(IDs.PLAN_CUTERIBBON, 1)]
kuzaratFacility2_treasure2 = [InternalItem(IDs.CHIPS_KINDAPERVY, 4)]
kuzaratFacility2_treasure3 = [InternalItem(IDs.BOOSTER_STR, 3)]
kuzaratFacility2_treasure4 = [InternalItem(IDs.SPCHARGER_P, 2)]
kuzaratFacility2_treasure5 = [InternalItem(IDs.PLAN_TUFFMIL, 1)]
kuzaratFacility2_treasure6 = [InternalItem(IDs.CHIPS_FAMOUSVOICE, 4)]

#Dungeon ID 11
rudArmsSewerN_treasure1 = [InternalItem(IDs.PLAN_REFLEX, 1), InternalItem(IDs.PLAN_NMTNMT, 1)]
rudArmsSewerN_treasure2 = [InternalItem(IDs.REFLEX, 3)]
rudArmsSewerN_treasure3 = [InternalItem(IDs.REFLEX, 2)]
rudArmsSewerN_treasure4 = [InternalItem(IDs.FRAGMENT_LIFE, 1), InternalItem(IDs.PLAN_ITEMDROPRATEUP, 1)]
rudArmsSewerN_treasure5 = [InternalItem(IDs.SPCHARGER, 2)]

#Dungeon ID 12
rudArmsSewerS_treasure1 = [InternalItem(IDs.PLAN_STUDDEDBRACELET, 1), InternalItem(IDs.PLAN_CUTEANIMALS, 1)]
rudArmsSewerS_treasure2 = [InternalItem(IDs.PLAN_STUDDEDARMLET, 1)]
rudArmsSewerS_treasure3 = [InternalItem(IDs.PLAN_MRRAT, 1)]
rudArmsSewerS_treasure4 = [InternalItem(IDs.FRAGMENT_LIFE, 2)]

#Dungeon ID 13
loweeCastleExterior_treasure1 = [InternalItem(IDs.PLAN_BEAMKATANA, 1)]
loweeCastleExterior_treasure2 = [InternalItem(IDs.PLAN_MECHANICALSWORD, 1)]
loweeCastleExterior_treasure3 = [InternalItem(IDs.FRAGMENT_LIFE, 1)]
loweeCastleExterior_treasure4 = [InternalItem(IDs.HEALING_GRASS, 3)]
loweeCastleExterior_treasure5 = [InternalItem(IDs.HEALING_POD, 2)]

#Dungeon ID 14
loweeCastleInterior_treasure1 = [InternalItem(IDs.HEALING_GRASS, 2)]
loweeCastleInterior_treasure2 = [InternalItem(IDs.HEALING_POD, 2)]
loweeCastleInterior_treasure3 = [InternalItem(IDs.SPCHARGER, 2)]
loweeCastleInterior_treasure4 = [InternalItem(IDs.DETOXIN, 2)]
loweeCastleInterior_treasure5 = [InternalItem(IDs.PARALAXIN, 2)]

#Dungeon ID 15
undergroundCave_treasure1 = [InternalItem(IDs.PLAN_BLADEDHAMMER, 1)]
undergroundCave_treasure2 = [InternalItem(IDs.PLAN_EJECTBUTTON, 1)]
undergroundCave_treasure3 = [InternalItem(IDs.PLAN_EXUBERANTFRAGMENT, 1)]
undergroundCave_treasure4 = [InternalItem(IDs.HEALING_DRINK, 2)]
undergroundCave_treasure5 = [InternalItem(IDs.CHIPS_HOVERMOVEMENT, 4)]

#Dungeon ID 16
castleChambers_treasure1 = [InternalItem(IDs.TUFFMIL, 3)]
castleChambers_treasure2 = [InternalItem(IDs.HEALING_POD, 2)]
castleChambers_treasure3 = [InternalItem(IDs.SPCHARGER, 3)]
castleChambers_treasure4 = [InternalItem(IDs.SPCHARGER_P, 4)]
castleChambers_treasure5 = [InternalItem(IDs.FRAGMENT_LIFE, 1)]

#Dungeon ID 17
gigoMainEntrance_treasure1 = [InternalItem(IDs.PLAN_MRRABBIT, 1)]
gigoMainEntrance_treasure2 = [InternalItem(IDs.PLAN_BASICHAMMER, 1)]
gigoMainEntrance_treasure3 = [InternalItem(IDs.PLAN_HEALINGDRINK, 1)]
gigoMainEntrance_treasure4 = [InternalItem(IDs.PLAN_SILVERANKLET, 1)]
gigoMainEntrance_treasure5 = [InternalItem(IDs.PLAN_HITTINGPATCH, 1)]

#Dungeon ID 18
gigoDepths_treasure1 = [InternalItem(IDs.PLAN_WISHBAND, 1)]
gigoDepths_treasure2 = [InternalItem(IDs.HEALING_POD, 2)]
gigoDepths_treasure3 = [InternalItem(IDs.SPCHARGER_P, 1)]
gigoDepths_treasure4 = [InternalItem(IDs.FRAGMENT_LIFE, 1)]
gigoDepths_treasure5 = [InternalItem(IDs.FRAGMENT_LIFE, 2)]

testTreasure = [InternalItem(IDs.ARMOR_EXEQUIP, 1), InternalItem(IDs.FRAGMENT_LUMP, 17), InternalItem(IDs.HEALING_DRINK, 1), InternalItem(IDs.WEAPON_EXCALIBUR, 1)]


# Regular Monsters
dogooDrop = [InternalItem(IDs.MAT_DOGOOJELLY, 1)]
metalDogooDrop = [InternalItem(IDs.MAT_METALJELLY, 1)]
hereticalDogooDrop = [InternalItem(IDs.MAT_HERETICALJELLY, 1)]
redDogooDrop = [InternalItem(IDs.MAT_ORANGEJELLY, 1)]
healDogooDrop = [InternalItem(IDs.MAT_GELFEELER, 1)]
healingDogooDrop = [InternalItem(IDs.MAT_REDGELFEELER, 1)]
highHealDogooDrop = [InternalItem(IDs.MAT_BLACKGELFEELER, 1)]
numbDogooDrop = [InternalItem(IDs.MAT_NUMBJELLY, 1)]
magicDogooDrop = [InternalItem(IDs.MAT_MAGICALJELLY, 1)]
jellyfishDogooDrop = [InternalItem(IDs.MAT_GELFEELER, 1)]
magicalDogooDrop = [InternalItem(IDs.MAT_MAGICALJELLY, 1)]
paralyzeDogooDrop = [InternalItem(IDs.MAT_NUMBJELLY, 1)]
shoebillDrop = [InternalItem(IDs.MAT_LARGEBEAK, 1)]
paradiseAvianDrop = [InternalItem(IDs.MAT_RAINBOWWING, 1)]
rukhDrop = [InternalItem(IDs.MAT_VERYLARGEBEAK, 1)]
nueDrop = [InternalItem(IDs.MAT_MAGICALBEAK, 1)]
viralShoebillDrop = [InternalItem(IDs.MAT_LARGEBEAK, 1)]
viralParadiseAvianDrop = [InternalItem(IDs.MAT_RAINBOWWING, 1)]
viralRukhDrop = [InternalItem(IDs.MAT_VERYLARGEBEAK, 1)]
viralNueDrop = [InternalItem(IDs.MAT_MAGICALBEAK, 1)]
viralEerieBirdDrop = [InternalItem(IDs.MAT_PHANTOMBIRDWING, 1)]
bitDrop = [InternalItem(IDs.MAT_SMALLCONDUCTOR, 1)]
customBitDrop = [InternalItem(IDs.MAT_ILLEGALCONDUCTOR, 1)]
highBitDrop = [InternalItem(IDs.MAT_ILLEGALGADGET, 1)]
highBitCustomDrop = [InternalItem(IDs.MAT_ILLEGALDEVICE, 1)]
nextGenBitDrop = [InternalItem(IDs.MAT_ILLEGALTECH, 1)]
bugDrop = [InternalItem(IDs.MAT_ILLEGALTECH, 1)]
supportBitDrop = [InternalItem(IDs.MAT_ILLEGALSSD, 1)]
iceSkeletonDrop = [InternalItem(IDs.MAT_ICEBONE, 1)]
skeletonDrop = [InternalItem(IDs.MAT_BONEFRAGMENT, 1)]
frozenSkullDrop = [InternalItem(IDs.MAT_ICESKELETON, 1)]
woodSkeletonDrop = [InternalItem(IDs.MAT_STRONGWOOD, 1)]
flameSkeletonDrop = [InternalItem(IDs.MAT_FLAMINBONE, 1)]
blazingSkeletonDrop = [InternalItem(IDs.MAT_MOLTENBONE, 1)]
skullDrop = [InternalItem(IDs.MAT_GOLDENTOOTH, 1)]
m3Drop = [InternalItem(IDs.MAT_CRUDECIRCUIT, 1)]
r4Drop = [InternalItem(IDs.MAT_ILLEGALMEMORY, 1)]
sdhcDrop = [InternalItem(IDs.MAT_ILLEGALROM, 1)]
dsttDrop = [InternalItem(IDs.MAT_ILLEGALHARDWARE, 1)]
edgeDrop = [InternalItem(IDs.MAT_ILLEGALRAM, 1)]
a2iDrop = [InternalItem(IDs.MAT_ILLEGALCONDUCTOR, 1)]
r4CustomDrop = [InternalItem(IDs.MAT_ILLEGALSSD, 1)]
rampagingM3Drop = [InternalItem(IDs.MAT_ILLEGALSSD, 1)]
autonomousArtilleryDrop = [InternalItem(IDs.MAT_ILLEGALMOTHERBOARD, 1)]
moddedDsttDrop = [InternalItem(IDs.MAT_ILLEGALMOTHERBOARD, 1)]
m3dDrop = [InternalItem(IDs.MAT_CRUDECIRCUIT, 1)]
sergeantFroggyDrop = [InternalItem(IDs.MAT_TEPPACHI, 1)]
frogInTheBoxDrop = [InternalItem(IDs.MAT_CARDBOARD, 1)]
pixelvaderDrop = [InternalItem(IDs.MAT_DOTANTENNA, 1)]
poxvaderDrop = [InternalItem(IDs.MAT_ROUNDANTENNA, 1)]
nanovaderDrop = [InternalItem(IDs.MAT_CELLANTENNA, 1)]
malvaderDrop = [InternalItem(IDs.MAT_NICEANTENNA, 1)]
invaderDrop = [InternalItem(IDs.MAT_UFOCONTROLLER, 1)]
crystalGolemDrop = [InternalItem(IDs.MAT_CRYSTALSKULL, 1)]
iceGolemDrop = [InternalItem(IDs.MAT_ICECRYSTAL, 1)]
earthGolemDrop = [InternalItem(IDs.MAT_EARTHCRYSTAL, 1)]
ruinGuardianDrop = [InternalItem(IDs.MAT_MAGICALCORE, 1)]
missileGolemDrop = [InternalItem(IDs.MAT_MITHRILORE, 1)]
seaGolemDrop = [InternalItem(IDs.MAT_WATERCRYSTAL, 1)]
forestGuardianDrop = [InternalItem(IDs.MAT_EARTHCRYSTAL, 1)]
blazeGolemDrop = [InternalItem(IDs.MAT_FIRECRYSTAL, 1)]
viralCrystalGolemDrop = [InternalItem(IDs.MAT_CRYSTALSKULL, 1)]
viralIceGolemDrop = [InternalItem(IDs.MAT_ICECRYSTAL, 1)]
viralEarthGolemDrop = [InternalItem(IDs.MAT_EARTHCRYSTAL, 1)]
viralRuinGuardianDrop = [InternalItem(IDs.MAT_MAGICALCORE, 1)]
viralMissleGolemDrop = [InternalItem(IDs.MAT_MITHRILORE, 1)]
viralSeaGolemDrop = [InternalItem(IDs.MAT_WATERCRYSTAL, 1)]
viralForestGolemDrop = [InternalItem(IDs.MAT_EARTHCRYSTAL, 1)]
viralBlazeGolemDrop = [InternalItem(IDs.MAT_FIRECRYSTAL, 1)]
cardbirdDrop = [InternalItem(IDs.MAT_BIRDSBRONZECROWN, 1)]
boxbirdDrop = [InternalItem(IDs.MAT_BOXBIRDWING, 1)]
princeCardbirdDrop = [InternalItem(IDs.MAT_BIRDSSILVERCROWN, 1)]
kingCardbirdDrop = [InternalItem(IDs.MAT_BIRDSKINGLYCROWN, 1)]
kingBoxbirdDrop = [InternalItem(IDs.MAT_COOLBOXBIRDWING, 1)]
princeBoxbirdDrop = [InternalItem(IDs.MAT_NICEBOXBIRDWING, 1)]
childWolfDrop = [InternalItem(IDs.MAT_WOLFFUR, 1)]
hyenaDrop = [InternalItem(IDs.MAT_HYENAPELT, 1)]
wolfDrop = [InternalItem(IDs.MAT_WOLFPELT, 1)]
wildDogDrop = [InternalItem(IDs.MAT_SHARPFANG, 1)]
coyoteDrop = [InternalItem(IDs.MAT_SHARPFANG, 1)]
grayWolfDrop = [InternalItem(IDs.MAT_SOFTWOLFFUR, 1)]
viralChildWolfDrop = [InternalItem(IDs.MAT_WOLFFUR, 1)]
viralHyenaDrop = [InternalItem(IDs.MAT_HYENAPELT, 1)]
viralWolfDrop = [InternalItem(IDs.MAT_WOLFPELT, 1)]
viralWildDogDrop = [InternalItem(IDs.MAT_SHARPFANG, 1)]
viralCoyoteDrop = [InternalItem(IDs.MAT_SHARPFANG, 1)]
viralGrayWolfDrop = [InternalItem(IDs.MAT_SOFTWOLFFUR, 1)]
cutekittyDrop = [InternalItem(IDs.MAT_KUPOCATCLAW, 1)]
leanTunaDrop = [InternalItem(IDs.MAT_CATWHISKER, 1)]
kupokittyDrop = [InternalItem(IDs.MAT_KUPOKITTYCLAWS, 1)]
meowDrop = [InternalItem(IDs.MAT_MEOWCLAWS, 1)]
tomDrop = [InternalItem(IDs.MAT_CATPAW, 1)]
palShellDrop = [InternalItem(IDs.MAT_BUFFSTONE, 1)]
magicStoneDrop = [InternalItem(IDs.MAT_MAGICALSTONE, 1)]
magmaStoneDrop = [InternalItem(IDs.MAT_MOLTENSTONE, 1)]
tulipDrop Drop = [InternalItem(IDs.MAT_)]
apeldoomDrop = [InternalItem(IDs.MAT_REDPETAL, 1)]
aimableDrop = [InternalItem(IDs.MAT_RAINBOWPETAL, 1)]
crackTailDrop = [InternalItem(IDs.MAT_YELLOWPETAL, 1)]
blueSunDrop = [InternalItem(IDs.MAT_BLUESEED, 1)]
cassTrapDrop = [InternalItem(IDs.MAT_TULIPSTAMEN, 1)]
alfredDrop = [InternalItem(IDs.MAT_REDPETAL, 1)]
clydeDrop = [InternalItem(IDs.MAT_RAG, 1)]
iceBoyDrop = [InternalItem(IDs.MAT_FROZENCLOTH, 1)]
coldBoyDrop = [InternalItem(IDs.MAT_FROZENCLOTH, 1)]
pinkyDrop = [InternalItem(IDs.MAT_INVISIBLECLOTH, 1)]
inkyDrop = [InternalItem(IDs.MAT_VENOMOUSCLOTH, 1)]
lostBoyDrop = [InternalItem(IDs.MAT_LOSTHOLYCLOTH, 1)]
blinkyDrop = [InternalItem(IDs.MAT_HEATCLOTH, 1)]
magmaBoyDrop = [InternalItem(IDs.MAT_HEATCLOTH, 1)]
bashfulDrop = [InternalItem(IDs.MAT_WATERSOLUBLECLOTH, 1)]
blazeBoyDrop = [InternalItem(IDs.MAT_FLAMINCLOTH, 1)]
deathBoyDrop = [InternalItem(IDs.MAT_DEATHCLOTH, 1)]
msClydeDrop = [InternalItem(IDs.MAT_BLUERIBBON, 1)]
iceGirlDrop = [InternalItem(IDs.MAT_PINKRIBBON, 1)]
coldGirlDrop = [InternalItem(IDs.MAT_PINKRIBBON, 1)]
msPinkyDrop = [InternalItem(IDs.MAT_INVISIBLERIBBON, 1)]
msInkyDrop = [InternalItem(IDs.MAT_VENOMRIBBON, 1)]
lostGirlDrop = [InternalItem(IDs.MAT_LOSTRIBBON, 1)]
msBlinkyDrop = [InternalItem(IDs.MAT_BLACKRIBBON, 1)]
magmaGirlDrop = [InternalItem(IDs.MAT_BLACKRIBBON, 1)]
msBashfulDrop = [InternalItem(IDs.MAT_PINKRIBBON, 1)]
blazeGirlDrop = [InternalItem(IDs.MAT_FLAMINRIBBON, 1)]
deathGirlDrop = [InternalItem(IDs.MAT_YELLOWRIBBON, 1)]
sunfloweryDrop = [InternalItem(IDs.MAT_SUNFLOWERYSEED, 1)]
moulinRougeDrop = [InternalItem(IDs.MAT_REDSEED, 1)]
orangeFlowerDrop = [InternalItem(IDs.MAT_ORANGEPETAL, 1)]
hikkyDrop = [InternalItem(IDs.MAT_NEGATIVESAP, 1)]
sentientreeDrop = [InternalItem(IDs.MAT_NEGATIVEROOT, 1)]
insatiableTreeDrop = [InternalItem(IDs.MAT_NEGATIVEBARK, 1)]
somethingTreeDrop = [InternalItem(IDs.MAT_SHAKINGLEAF, 1)]
viralHikkyDrop = [InternalItem(IDs.MAT_NEGATIVESAP, 1)]
viralSentientreeDrop = [InternalItem(IDs.MAT_NEGATIVEROOT, 1)]
viralInsatiableTreeDrop = [InternalItem(IDs.MAT_NEGATIVEBARK, 1)]
viralSomethingTreeDrop = [InternalItem(IDs.MAT_SHAKINGLEAF, 1)]
deusManDrop = [InternalItem(IDs.MAT_YOUTHHEART, 1)]
strangePersonDrop = [InternalItem(IDs.MAT_WICKEDHEART, 1)]
oldManDeusDrop = [InternalItem(IDs.MAT_OLDMANSPATHOS, 1)]
bundodoOldManDrop = [InternalItem(IDs.MAT_HOBBYSOUL, 1)]
oldDeathDrop = [InternalItem(IDs.MAT_AGINGROMANTICISM, 1)]
alrauneDrop = [InternalItem(IDs.MAT_MYSTERIOUSPETAL, 1)]
alunaDrop = [InternalItem(IDs.MAT_MYSTERIOUSPETAL, 1)]
aluneDrop = [InternalItem(IDs.MAT_MYSTERIOUSPETAL, 1)]
rafflesiaDrop = [InternalItem(IDs.MAT_POISONOUSPETAL, 1)]
forestSpiritDrop = [InternalItem(IDs.MAT_MYSTERIOUSPETAL, 1)]
flameFlowerDrop = [InternalItem(IDs.MAT_BURNINGPETAL, 1)]
flowerFairyDrop = [InternalItem(IDs.MAT_MYSTERIOUSPETAL, 1)]
viralAlrauneDrop = [InternalItem(IDs.MAT_MYSTERIOUSPETAL, 1)]
viralAlunaDrop = [InternalItem(IDs.MAT_MYSTERIOUSPETAL, 1)]
viralAluneDrop = [InternalItem(IDs.MAT_MYSTERIOUSPETAL, 1)]
viralRafflesiaDrop = [InternalItem(IDs.MAT_POISONOUSPETAL, 1)]
viralForestSpiritDrop = [InternalItem(IDs.MAT_MYSTERIOUSPETAL, 1)]
viralFlameFlowerDrop = [InternalItem(IDs.MAT_BURNINGPETAL, 1)]
viralFlowerFairyDrop = [InternalItem(IDs.MAT_MYSTERIOUSPETAL, 1)]
contractedAngelDrop = [InternalItem(IDs.MAT_MYSTERIOUSHALO, 1)]
lightbulbAngelDrop = [InternalItem(IDs.MAT_MYSTERIOUSREDBALL, 1)]
cuberialDrop = [InternalItem(IDs.MAT_SOULCONTRACT, 1)]
hachibeiDrop = [InternalItem(IDs.MAT_MAGICALCONTRACT, 1)]
promiseRingDrop = [InternalItem(IDs.MAT_INSANECONTRACT, 1)]
promiseKeeperDrop = [InternalItem(IDs.MAT_CONTRACTEDBALL, 1)]
fungusDrop = [InternalItem(IDs.MAT_FUNGUSSSPORES, 1)]
matangoDrop = [InternalItem(IDs.MAT_MATANGOSSPORES, 1)]
lizardmanDrop = [InternalItem(IDs.MAT_LIZARDSCALE, 1)]
heavyDragoonDrop = [InternalItem(IDs.MAT_MAGICALFRAGMENT, 1)]
goldLizardDrop = [InternalItem(IDs.MAT_FROZENSCALE, 1)]
dragonWarriorDrop = [InternalItem(IDs.MAT_KNIGHTEDSCALE, 1)]
deathStalkerDrop = [InternalItem(IDs.MAT_JETBLACKSCALE, 1)]
iceLizardDrop = [InternalItem(IDs.MAT_EARTHSCALE, 1)]
dragonKnightDrop = [InternalItem(IDs.MAT_KNIGHTEDSCALE, 1)]
highLizardDrop = [InternalItem(IDs.MAT_BLACKLIGHTSCALE, 1)]
lizardKnightDrop = [InternalItem(IDs.MAT_MAGICALFRAGMENT, 1)]
dinosauroidDrop = [InternalItem(IDs.MAT_SUPERHARDSCALE, 1)]
dragoniaDrop = [InternalItem(IDs.MAT_KNIGHTEDSCALE, 1)]
viralHeavyDragoonDrop = [InternalItem(IDs.MAT_MAGICALFRAGMENT, 1)]
viralGoldLizardDrop = [InternalItem(IDs.MAT_FROZENSCALE, 1)]
viralDragonWarriorDrop = [InternalItem(IDs.MAT_KNIGHTEDSCALE, 1)]
viralDeathStalkerDrop = [InternalItem(IDs.MAT_JETBLACKSCALE, 1)]
viralIceLizardDrop = [InternalItem(IDs.MAT_EARTHSCALE, 1)]
viralHighLizardDrop = [InternalItem(IDs.MAT_BLACKLIGHTSCALE, 1)]
viralLizardKnightDrop = [InternalItem(IDs.MAT_MAGICALFRAGMENT, 1)]
viralDragonKnightDrop = [InternalItem(IDs.MAT_KNIGHTEDSCALE, 1)]
viralDinosauroidDrop = [InternalItem(IDs.MAT_SUPERHARDSCALE, 1)]
viralDragoniaDrop = [InternalItem(IDs.MAT_KNIGHTEDSCALE, 1)]
delinquentCatDrop = [InternalItem(IDs.MAT_GANGMASK, 1)]
ruffianCatDrop = [InternalItem(IDs.MAT_HOODLUMMASK, 1)]
ganglordPantherDrop = [InternalItem(IDs.MAT_GANGLORDMASK, 1)]
boxerCatDrop = [InternalItem(IDs.MAT_CATGLOVES, 1)]
createdSoldierDrop = [InternalItem(IDs.MAT_IRONFRAGMENT, 1)]
loweeDefenseGuardDrop = [InternalItem(IDs.MAT_IRONFRAGMENT, 1)]
loweeSoldierDrop = [InternalItem(IDs.MAT_IRONFRAGMENT, 1)]
loweeHighGuardDrop = [InternalItem(IDs.MAT_IRONFRAGMENT, 1)]
leanboxSoldierDrop = [InternalItem(IDs.MAT_IRONFRAGMENT, 1)]
loweeEliteGuardDrop = [InternalItem(IDs.MAT_IRONFRAGMENT, 1)]
loweeMagicalSoldierDrop = [InternalItem(IDs.MAT_SILVERFRAGMENT, 1)]
leanboxHighGuardDrop = [InternalItem(IDs.MAT_IRONFRAGMENT, 1)]
asicRemnantsDrop = [InternalItem(IDs.MAT_IRONFRAGMENT, 1)]
volcanoCrabDrop = [InternalItem(IDs.MAT_BLAZINGORE, 1)]
magmaCrabDrop = [InternalItem(IDs.MAT_MOLTENSTONE, 1)]
mountainSeoiDrop = [InternalItem(IDs.MAT_MAGICALSTONE, 1)]
viralVolcanoCrabDrop = [InternalItem(IDs.MAT_BLAZINGORE, 1)]
viralMagmaCrabDrop = [InternalItem(IDs.MAT_MOLTENSTONE, 1)]
viralMountainSeoiDrop = [InternalItem(IDs.MAT_MAGICALSTONE, 1)]
tokimekiSisterDrop = [InternalItem(IDs.MAT_TOKIMEKI, 1)]
fetigalDrop = [InternalItem(IDs.MAT_BLACKBOXSET, 1)]
teraHunkDrop = [InternalItem(IDs.MAT_INDULGENCE, 1)]
shimamosBrotherDrop = [InternalItem(IDs.MAT_CONNECTINGHOOK, 1)]
spiderDrop = [InternalItem(IDs.MAT_SPIDERWEB, 1)]
tarantulaDrop = [InternalItem(IDs.MAT_VENOMOUSSPIDERWEB, 1)]
megaSpiderDrop = [InternalItem(IDs.MAT_ELASTICTHREAD, 1)]
demonSpiderDrop = [InternalItem(IDs.MAT_STRONGTHREAD, 1)]
queenSpiderDrop = [InternalItem(IDs.MAT_FRAGRANTTHREAD, 1)]
numbingSpiderDrop = [InternalItem(IDs.MAT_PARALYSISWEB, 1)]
blackSpiderDrop = [InternalItem(IDs.MAT_STRONGTHREAD, 1)]
plummetDrop = [InternalItem(IDs.MAT_PLUMMETPIECE, 1)]
plammetDrop = [InternalItem(IDs.MAT_PLAMMETPIECE, 1)]
plommetDrop = [InternalItem(IDs.MAT_PLOMMETPIECE, 1)]
plumindigoDrop = [InternalItem(IDs.MAT_PLUMINDIGOPIECE, 1)]
spottedPlummetDrop = [InternalItem(IDs.MAT_SPLUMMETPIECE, 1)]
dogoneDrop = [InternalItem(IDs.MAT_HARDMETPIECE, 1)]
teritsDrop = [InternalItem(IDs.MAT_PURPLEBLOCK, 1)]
testriDrop = [InternalItem(IDs.MAT_YELLOWBLOCK, 1)]
teristDrop = [InternalItem(IDs.MAT_GREENBLOCK, 1)]
tetrisiDrop = [InternalItem(IDs.MAT_STRANGLEDLUMP, 1)]
radisherDrop = [InternalItem(IDs.MAT_RADISHERLEAF, 1)]
carroteerDrop = [InternalItem(IDs.MAT_CARROTEERLEAF, 1)]
horsebirdDrop = [InternalItem(IDs.MAT_HORSEBIRDFEATHER, 1)]
horsebirdCAWDrop = [InternalItem(IDs.MAT_HORSEBIRDTHIGH, 1)]
swallowtailDrop = [InternalItem(IDs.MAT_BIGBUTTERFLYWING, 1)]
fairyflyDrop = [InternalItem(IDs.MAT_PHANTOMWING, 1)]
speckleDrop = [InternalItem(IDs.MAT_TINYOUTFIT, 1)]
cyberflyDrop = [InternalItem(IDs.MAT_ELECTRICWING, 1)]
viralSwallowtailDrop = [InternalItem(IDs.MAT_BIGBUTTERFLYWING, 1)]
viralSpeckleDrop = [InternalItem(IDs.MAT_TINYOUTFIT, 1)]
viralFairyflyDrop = [InternalItem(IDs.MAT_PHANTOMWING, 1)]
viralCyberflyDrop = [InternalItem(IDs.MAT_ELECTRICWING, 1)]
coinManDrop = [InternalItem(IDs.MAT_COINFRAGMENT, 1)]
exhaustedJellyDrop = [InternalItem(IDs.MAT_FANCYJELLY, 1)]
boomerangDrop = [InternalItem(IDs.MAT_BLOODYBOOMERANG, 1)]
wdHeadDrop = [InternalItem(IDs.MAT_WDFRAGMENT, 1)]
penguinDrop = [InternalItem(IDs.MAT_SLIPPERYWING, 1)]
normalShampuruDrop = [InternalItem(IDs.MAT_SHAMPURUEAR, 1)]
buffShampuruDrop = [InternalItem(IDs.MAT_SHAMPURUEAR, 1)]
magicalShampuruDrop = [InternalItem(IDs.MAT_SHAMPURUEAR, 1)]
ancientDragonDrop = [InternalItem(IDs.MAT_OLDDRAGONORB, 1)]
nidhoggDrop = [InternalItem(IDs.MAT_OLDDRAGONHORN, 1)]
elementalDragonDrop = [InternalItem(IDs.MAT_DRAGONCLAWS, 1)]
ruinsDragonDrop = [InternalItem(IDs.MAT_OLDDRAGONBALL, 1)]
crescentDragonDrop = [InternalItem(IDs.MAT_OLDDRAGONHUH, 1)]
lostDragonDrop = [InternalItem(IDs.MAT_ANCIENTTHING, 1)]
dolphinDrop = [InternalItem(IDs.MAT_DOLPHINTAIL, 1)]
plaidDolphinDrop = [InternalItem(IDs.MAT_PLAIDDOLPHINTAIL, 1)]
cyberDolphinDrop = [InternalItem(IDs.MAT_ELECTRICFIN, 1)]
dolichorhynchopsDrop = [InternalItem(IDs.MAT_DOLPHINCHECKTAIL, 1)]
thousandYearDolphinDrop = [InternalItem(IDs.MAT_QUALITYDOLPHINTAIL, 1)]
phoenixDrop = [InternalItem(IDs.MAT_PHOENIXWING,), InternalItem(IDs.HEADBAND_HISTY, 1)]
rocDrop = [InternalItem(IDs.MAT_PHANTOMBIRDWING, 1)]


# ???
gypsDrop = [InternalItem(IDs.MAT_PHANTOMBIRDWING, 1)]
autoSurveillanceDrop = [InternalItem(IDs.MAT_ILLEGALROM, 1)]


# Large Medal Monster
