from importlib import reload
import typing
from ..LocationData import LocationData
from ..names.DungeonNames import *
Quests: typing.List[LocationData] = (
LocationData([virtua_forest_safe_zone],"Dogoo Damage!", 1, "Quest"),
LocationData([otori_forest],"[Urgent] Verification", 2, "Quest"),
LocationData([otori_forest],"[Donate] Will He See Me?", 3, "Quest"),
LocationData([otori_forest],"[Bond] Best Ingredient", 4, "Quest"),
LocationData([otori_forest],"Lovely Rice", 5, "Quest"),
LocationData([wanderers_cave],"[Urgent] Demon Treasure", 6, "Quest"),
LocationData([jet_set_range, jet_set_peak],"Save Her!", 7, "Quest"),
LocationData([lowee_castle_exterior, lowee_castle_interior],"Rock Soul", 8, "Quest"),
LocationData([kuzarat_facility_1, kuzarat_facility_2],"[Machine] Robo Machine", 9, "Quest"),
LocationData([lowee_castle_interior, kobaba_ruins],"Mid-Age Blues", 10, "Quest"),
LocationData([gigo_main_entrance],"[Mistaken] Greeting?", 11, "Quest"),
LocationData([national_factory],"[Envy] Detestable", 12, "Quest"),
LocationData([metroid_shelter],"[Fierce] Flame Wolf", 13, "Quest"),
LocationData([magma_cave, magma_cave_depths],"[Arrogance] Kingly", 14, "Quest"),
LocationData([magma_cave_depths],"Marrow Burns", 15, "Quest"),
LocationData([reload_grasslands],"[Isolation] The League", 16, "Quest"),
LocationData([bandicrash, halo_forest],"Ultimate Ingredient?", 17, "Quest"),
LocationData([lowee_castle_interior, lowee_castle_exterior],"Demon Sword Crafting", 18, "Quest"),
LocationData([zega_forest],"First Trial", 19, "Quest"),
LocationData([ario_plateau],"Real Dream", 20, "Quest"),
LocationData([graphic_pass, graphic_pass_peak],"Stairway to the Heavens", 21, "Quest", 2),
LocationData([virtua_forest_safe_zone],"My Summer Vacation", 22, "Quest"),
LocationData([virtua_forest_safe_zone],"Scent Fetish", 23, "Quest"),
LocationData([station_area],"I Hate Robo", 24, "Quest"),
LocationData([station_area],"Pure 2 Heart", 25, "Quest"),
LocationData([zeca_ruins_no1],"Shiny Quest", 26, "Quest"),
LocationData([otori_forest],"Dont Wanna Work", 27, "Quest"),
LocationData([zeca_ruins_no2],"Shampuru!", 28, "Quest"),
LocationData([jet_set_range, jet_set_peak],"The Eastern Field", 29, "Quest"),
LocationData([jet_set_range, jet_set_peak],"My Liege", 30, "Quest"),
LocationData([jet_set_range],"Mix and Mix Well", 31, "Quest", 1),
LocationData([wanderers_cave],"Dogs Are Hot", 32, "Quest"),
LocationData([wanderers_cave],"KOMO's Kitchen", 33, "Quest"),
LocationData([wanderers_cave, wanderers_cave_depths],"Random Intentions", 34, "Quest"),
LocationData([wanderers_cave, wanderers_cave_depths],"An Evolving Tomorrow", 35, "Quest", 2),
LocationData([bandicrash, digital_future_land],"Bourbon", 36, "Quest"),
LocationData([zeca_ruins_no2],"Shampuru Festival!", 37, "Quest"),
LocationData([zeca_ruins_no2],"Trade Pass", 38, "Quest"),
LocationData([kuzarat_facility_1, kuzarat_facility_2, pii_shii_game_factory],"Underground", 39, "Quest"),
LocationData([kuzarat_facility_2],"Mushrooms vs Bamboo", 40, "Quest"),
LocationData([soni_wetlands],"Protagonist Requisites", 41, "Quest", 2),
LocationData([soni_wetlands, so_shal_forest],"They're on the move!", 42, "Quest"),
LocationData([soni_wetlands],"Challenger", 43, "Quest", 1),
LocationData([rud_arms_sewer_n],"Eliminate Firearms", 44, "Quest"),
LocationData([rud_arms_sewer_n],"The Famous 'That'", 45, "Quest", 2),
LocationData([reload_grasslands],"Getting Seven Together", 46, "Quest"),
LocationData([lowee_castle_interior, kobaba_ruins],"Suspicious Folks", 47, "Quest"),
LocationData([lowee_castle_exterior],"Hina Doll", 48, "Quest"),
LocationData([lowee_castle_exterior],"Arrogant New CPU", 49, "Quest"),
LocationData([underground_cave, castle_chambers],"Rare Guitar Controller", 50, "Quest", 2),
LocationData([underground_cave, castle_chambers],"Forced Friendliness", 51, "Quest", 1),
LocationData([underground_cave, castle_chambers, virtua_forest],"A Heavy Request!", 52, "Quest"),
LocationData([underground_cave, castle_chambers, national_factory],"Really", 53, "Quest"),
LocationData([suaho_mountain_range],"Clean Kill Repeat", 54, "Quest"),
LocationData([suaho_mountain_range],"Waterproof Robot", 55, "Quest", 1),
LocationData([suaho_mountain_range],"7 Sparkling Lights", 56, "Quest"),
LocationData([soni_wetlands],"Expensive Absence", 57, "Quest"),
LocationData([gigo_depths, gigo_main_entrance],"Strong Crab", 58, "Quest"),
LocationData([gigo_main_entrance],"Beansprout Challenge", 59, "Quest"),
LocationData([gigo_depths, lowee_castle_southern_space],"Arfoire Ban", 60, "Quest"),
LocationData([gigo_main_entrance],"New Parts in Stock!?", 61, "Quest", 1),
LocationData([halo_forest],"The Legendary!?", 62, "Quest"),
#LocationData([Aaaaa],"aaaaaaa", 63, "Quest"), # Missing Quest
LocationData([halo_forest],"Poison Position", 64, "Quest"),
LocationData([halo_forest],"Nursing", 65, "Quest", 1),
LocationData([adaldik_forest],"The Star-Seeker", 66, "Quest"),
LocationData([adaldik_forest],"New Hair Ornament", 67, "Quest"),
LocationData([adaldik_forest],"Universal Buddy", 68, "Quest", 1),
LocationData([adaldik_forest],"Expensive Box", 69, "Quest"),
LocationData([national_factory],"Ran Ran", 70, "Quest"),
LocationData([mines],"Revenge", 71, "Quest"),
LocationData([mines],"Spec-Buster?", 72, "Quest", 1),
LocationData([mines],"Not Defective", 73, "Quest", 2),
LocationData([lowee_castle_southern_space],"Giant Cans", 74, "Quest"),
LocationData([lowee_castle_southern_space],"Magical Girl Request", 75, "Quest"),
LocationData([station_area],"Getting Creeped Up On", 76, "Quest", 1),
LocationData([lowee_castle_southern_space],"Golem Creation", 77, "Quest"),
#LocationData([Aaaaa],"aaaaaaa", 78, "Quest"), # Missing Quest
LocationData([zega_forest],"Evil Classroom", 79, "Quest"),
LocationData([ps_dimension],"A Real Idiot", 80, "Quest"),
LocationData([ps_dimension],"Arise! NEETs!", 81, "Quest"),
LocationData([ps_dimension],"Retirement Regrets", 82, "Quest"),
LocationData([haneda_mountain_range],"Ew Carrots!", 83, "Quest"),
LocationData([haneda_mountain_range],"To Be a Bone Master", 84, "Quest"),
LocationData([kobaba_ruins],"Bonds are LOVE!", 85, "Quest", 1),
LocationData([metroid_shelter],"Whats in Clay Pipes", 86, "Quest"),
LocationData([magma_cave, metroid_shelter],"I Wanna Beat Her!", 87, "Quest"),
LocationData([metroid_shelter_depths],"Training Regimen 1", 88, "Quest", 1),
LocationData([metroid_shelter, magma_cave],"Ultimate Cooking Items", 89, "Quest"),
LocationData([metroid_shelter_depths],"Ill Mess Stuff Up!", 90, "Quest"),
LocationData([luji_plateau],"Super Happy", 91, "Quest"),
LocationData([luji_plateau],"Unchanging Weakness", 92, "Quest"),
LocationData([luji_plateau],"Knock 'Em All Out!", 93, "Quest"),
LocationData([metroid_shelter],"I Want To Go Public!", 94, "Quest", 2),
LocationData([luji_plateau],"Angelic Curses", 95, "Quest"),
LocationData([ario_plateau],"A Fun Contract", 96, "Quest"),
LocationData([ario_plateau],"What Is the Best?", 97, "Quest"),
LocationData([otori_cave],"That Badge", 98, "Quest"),
LocationData([kobaba_ruins],"Combat Training", 99, "Quest"),
LocationData([kobaba_ruins],"Aaaah Lady Vert", 100, "Quest"),
LocationData([kobaba_ruins, nekutoki_forest],"Crab of Misfortune", 101, "Quest"),
LocationData([anonydeaths_lab],"Lastation in Arms", 102, "Quest", 1),
LocationData([anonydeaths_lab_depths, anonydeaths_lab],"Soul! Hobby Soul!", 103, "Quest"),
LocationData([anonydeaths_lab_depths, anonydeaths_lab, station_area],"Arfoire Ban 2", 104, "Quest"),
LocationData([anonydeaths_lab],"He Who Loves Tanks", 105, "Quest"),
LocationData([anonydeaths_lab],"Robot Rage", 106, "Quest"),
LocationData([keraga_dimension],"Gimme Fin Soup", 107, "Quest"),
LocationData([keraga_dimension],"Tripping the Rift", 108, "Quest", 1),
LocationData([keraga_dimension],"Extracurriculars", 109, "Quest", 2),
LocationData([magma_cave],"Punish It", 110, "Quest"),
LocationData([magma_cave],"My Fantasy!", 111, "Quest"),
LocationData([magma_cave_depths, magma_cave],"Scared", 112, "Quest"),
LocationData([magma_cave],"Peerless Ingredients", 113, "Quest"),
LocationData([pii_shii_game_factory],"He Who Loves Tanks 2", 114, "Quest"),
LocationData([ario_plateau],"Submissive Students", 115, "Quest", 2),
LocationData([pii_shii_game_factory],"Cat Fur", 116, "Quest"),
LocationData([pii_shii_game_factory],"Wandering Scent Fetish", 117, "Quest"),
LocationData([extradimensional_space],"The CPU We Wished For", 118, "Quest"),
LocationData([extradimensional_space],"A Greeeeat Man!", 119, "Quest"),
LocationData([extradimensional_space],"Negotiation Failure", 120, "Quest"),
LocationData([extradimensional_space],"Infected Announcement!", 121, "Quest", 2),
LocationData([extradimensional_space],"Hate! Green!", 122, "Quest"),
LocationData([extradimensional_space],"Trap", 123, "Quest"),
LocationData([graphic_pass, graphic_pass_peak],"Stress Relief", 124, "Quest"),
LocationData([graphic_pass, graphic_pass_peak],"A Gas Trap", 125, "Quest"),
LocationData([graphic_pass, graphic_pass_peak],"Unfortunate Monster", 126, "Quest"),
LocationData([graphic_pass, graphic_pass_peak],"Rare Flute Maker", 127, "Quest"),
LocationData([graphic_pass, graphic_pass_peak],"Aging Romanticism", 128, "Quest"),
LocationData([graphic_pass],"Peerless Ingredients 2", 129, "Quest", 1),
LocationData([city_center],"Enemy in Town", 130, "Quest", 1),
LocationData([city_center],"That! You know!", 131, "Quest"),
LocationData([powerlevel_island, powerlevel_island_interior],"Summer Romance", 132, "Quest"),
LocationData([vida_dimension],"The Newest Weapon!?", 133, "Quest"),
LocationData([vida_dimension, duo_r_ruins],"A Secret Request", 134, "Quest"),
LocationData([lowee_castle_northern_space],"Magic Origins", 135, "Quest"),
LocationData([lowee_castle_northern_space],"He Who Loves Tanks 3", 136, "Quest"),
LocationData([so_shal_forest],"Bitter Tree Bark", 137, "Quest"),
LocationData([so_shal_forest],"Got It!", 138, "Quest", 1),
LocationData([em_es_magma_cave, em_es_magma_cave_depths],"Guards Also Train!", 139, "Quest"),
LocationData([em_es_magma_cave, em_es_magma_cave_depths],"Traded Circuits", 140, "Quest"),
LocationData([duo_r_ruins],"Cat Boxer", 141, "Quest"),
LocationData([duo_r_ruins],"A Genius Request", 142, "Quest"),
LocationData([duo_r_ruins],"Its Just Data!", 143, "Quest"),
LocationData([do_temple],"To Say Farewell", 144, "Quest"),
LocationData([do_temple],"Entropy Etc", 145, "Quest"),
LocationData([koagura_plateau],"Blooming Tragedy", 146, "Quest"),
#LocationData([Aaaaa],"Memory of That Day", 147, "Quest"),
)